"""agent-browser CLI wrapper with stealth configuration for anti-bot detection.

This module provides a Python wrapper around the agent-browser CLI (Vercel Labs)
with realistic headers generated by browserforge, fingerprint spoofing, and 
anti-detection measures to bypass bot detection on sites like homegate.ch.
"""

import json
import logging
import os
import shutil
import subprocess
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from browserforge.headers import HeaderGenerator, Browser

logger = logging.getLogger("macgent.agent_browser")


def generate_realistic_headers(
    browser_name: str = "chrome",
    min_version: int = 120,
    os_name: str = "macos",
    locale: list[str] | None = None,
    http_version: int = 2,
) -> dict[str, str]:
    """Generate realistic browser headers using browserforge.
    
    Args:
        browser_name: Browser name (chrome, firefox, safari, edge)
        min_version: Minimum browser version
        os_name: Operating system (macos, windows, linux)
        locale: List of locale preferences
        http_version: HTTP version (1, 2)
        
    Returns:
        Dictionary of realistic headers
    """
    if locale is None:
        # Based on user's timezone (Europe/Zurich)
        locale = ["en-US", "de-CH", "de", "en"]
    
    generator = HeaderGenerator(
        browser=Browser(name=browser_name, min_version=min_version),
        os=os_name,
        locale=locale,
        http_version=http_version,
    )
    return generator.generate()


# Chrome browser arguments for stealth mode
# Note: Only use args that don't conflict with Playwright's browser launch
STEALTH_BROWSER_ARGS = [
    "--disable-blink-features=AutomationControlled",
    "--disable-infobars",
    "--lang=en-US",
]


@dataclass
class StealthConfig:
    """Configuration for stealth browser settings."""
    
    browser_name: str = "chrome"
    browser_min_version: int = 120
    os_name: str = "macos"
    locale: list[str] = field(default_factory=lambda: ["en-US", "de-CH", "de", "en"])
    http_version: int = 2
    browser_args: list[str] = field(default_factory=lambda: STEALTH_BROWSER_ARGS)
    headed: bool = True  # Headed mode is harder to detect
    profile_path: str | None = None
    proxy: str | None = None
    color_scheme: str = "light"
    
    # Generated headers (cached)
    _headers: dict[str, str] | None = field(default=None, repr=False)
    _user_agent: str | None = field(default=None, repr=False)
    
    def get_headers(self) -> dict[str, str]:
        """Get realistic headers, generating them if needed."""
        if self._headers is None:
            self._headers = generate_realistic_headers(
                browser_name=self.browser_name,
                min_version=self.browser_min_version,
                os_name=self.os_name,
                locale=self.locale,
                http_version=self.http_version,
            )
        return self._headers
    
    def get_user_agent(self) -> str:
        """Get the User-Agent string from generated headers."""
        if self._user_agent is None:
            headers = self.get_headers()
            self._user_agent = headers.get("User-Agent", "")
        return self._user_agent
    
    def to_agent_browser_config(self) -> dict[str, Any]:
        """Convert to agent-browser config file format."""
        config: dict[str, Any] = {
            "headed": self.headed,
            "userAgent": self.get_user_agent(),
            "colorScheme": self.color_scheme,
        }
        if self.profile_path:
            config["profile"] = self.profile_path
        if self.proxy:
            config["proxy"] = self.proxy
        if self.browser_args:
            config["args"] = ",".join(self.browser_args)
        return config


# JavaScript to inject for fingerprint spoofing
FINGERPRINT_SPOOF_JS = """
// Override navigator.webdriver
Object.defineProperty(navigator, 'webdriver', { get: () => undefined });

// Override navigator.plugins with realistic plugins
Object.defineProperty(navigator, 'plugins', {
    get: () => [
        { name: 'Chrome PDF Plugin', filename: 'internal-pdf-viewer', description: 'Portable Document Format' },
        { name: 'Chrome PDF Viewer', filename: 'mhjfbmdgcfjbbpaeojofohoefgiehjai', description: '' },
        { name: 'Native Client', filename: 'internal-nacl-plugin', description: '' }
    ]
});

// Override navigator.languages
Object.defineProperty(navigator, 'languages', { get: () => ['en-US', 'en', 'de-CH', 'de'] });

// Override WebGL fingerprint
const getParameter = WebGLRenderingContext.prototype.getParameter;
WebGLRenderingContext.prototype.getParameter = function(parameter) {
    if (parameter === 37445) return 'Intel Inc.';
    if (parameter === 37446) return 'Intel Iris OpenGL Engine';
    return getParameter.call(this, parameter);
};

// Override canvas fingerprint with subtle noise
const originalToDataURL = HTMLCanvasElement.prototype.toDataURL;
HTMLCanvasElement.prototype.toDataURL = function(type) {
    if (type === 'image/png' && this.width === 220 && this.height === 30) {
        const ctx = this.getContext('2d');
        if (ctx) {
            const imageData = ctx.getImageData(0, 0, this.width, this.height);
            for (let i = 0; i < imageData.data.length; i += 4) {
                imageData.data[i] ^= (Math.random() * 2) | 0;
            }
            ctx.putImageData(imageData, 0, 0);
        }
    }
    return originalToDataURL.apply(this, arguments);
};

// Override AudioContext fingerprint
const originalAudioContext = window.AudioContext || window.webkitAudioContext;
if (originalAudioContext) {
    window.AudioContext = window.webkitAudioContext = function() {
        const ctx = new originalAudioContext();
        const originalCreateOscillator = ctx.createOscillator;
        ctx.createOscillator = function() {
            const oscillator = originalCreateOscillator.call(this);
            oscillator.frequency.value += Math.random() * 0.0001;
            return oscillator;
        };
        return ctx;
    };
}

// Override permissions API
const originalQuery = navigator.permissions?.query;
if (originalQuery) {
    navigator.permissions.query = function(parameters) {
        return Promise.resolve({ state: 'prompt', onchange: null });
    };
}

// Override connection info
Object.defineProperty(navigator, 'connection', {
    get: () => ({
        effectiveType: '4g',
        rtt: 50,
        downlink: 10,
        saveData: false
    })
});

// Override hardwareConcurrency
Object.defineProperty(navigator, 'hardwareConcurrency', { get: () => 8 });

// Override deviceMemory
Object.defineProperty(navigator, 'deviceMemory', { get: () => 8 });

// Override platform
Object.defineProperty(navigator, 'platform', { get: () => 'MacIntel' });

// Remove automation indicators
delete window.__webdriver_script_fn;
delete window.__driver_evaluate;
delete window.__webdriver_evaluate;
delete window.__selenium_evaluate;
delete window.__fxdriver_evaluate;
delete window.__driver_unwrapped;
delete window.__webdriver_unwrapped;
delete window.__selenium_unwrapped;
delete window.__fxdriver_unwrapped;
delete window.__webdriver_script_function;
delete window.__webdriver_script_func;
delete window.__webdriver_script_fn;
delete window.__$webdriverAsyncExecutor;
delete window.wrappedJSObject;

// Override chrome runtime
window.chrome = {
    runtime: {},
    loadTimes: function() {},
    csi: function() {},
    app: {}
};

console.log('[Stealth] Fingerprint spoofing injected');
"""


class AgentBrowser:
    """Python wrapper for the agent-browser CLI with stealth features."""
    
    def __init__(self, config: StealthConfig | None = None):
        self.config = config or StealthConfig()
        self._browser_path = self._find_agent_browser()
        self._config_file: Path | None = None
        self._is_open = False
        self._current_url: str | None = None
        
    def _find_agent_browser(self) -> str:
        """Find the agent-browser CLI executable."""
        # Check common locations
        candidates = [
            shutil.which("agent-browser"),
            os.path.expanduser("~/.npm-global/bin/agent-browser"),
            "/usr/local/bin/agent-browser",
            "/opt/homebrew/bin/agent-browser",
        ]
        for path in candidates:
            if path and Path(path).exists():
                logger.debug(f"Found agent-browser at: {path}")
                return path
        raise RuntimeError("agent-browser CLI not found. Install with: npm install -g agent-browser")
    
    def _write_config_file(self) -> Path:
        """Write a temporary config file for agent-browser."""
        config_data = self.config.to_agent_browser_config()
        config_file = Path(tempfile.mktemp(suffix=".json", prefix="agent-browser-config-"))
        config_file.write_text(json.dumps(config_data, indent=2))
        logger.debug(f"Wrote config file: {config_file}")
        return config_file
    
    def _run_command(self, *args: str, json_output: bool = False, timeout: float = 30.0) -> str:
        """Run an agent-browser command and return the output."""
        cmd = [self._browser_path]
        
        # Add config file if we have one
        if self._config_file:
            cmd.extend(["--config", str(self._config_file)])
        
        # Add JSON output flag if requested
        if json_output:
            cmd.append("--json")
        
        cmd.extend(args)
        
        logger.debug(f"Running: {' '.join(cmd)}")
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            if result.returncode != 0:
                error_msg = result.stderr.strip() or result.stdout.strip()
                logger.error(f"agent-browser error: {error_msg}")
                raise RuntimeError(f"agent-browser failed: {error_msg}")
            return result.stdout.strip()
        except subprocess.TimeoutExpired:
            raise RuntimeError(f"agent-browser command timed out: {' '.join(args)}")
    
    def start(self) -> "AgentBrowser":
        """Start the browser session with stealth configuration."""
        self._config_file = self._write_config_file()
        logger.info(f"Started agent-browser session with stealth config")
        logger.info(f"User-Agent: {self.config.get_user_agent()}")
        return self
    
    def open(self, url: str, extra_headers: dict[str, str] | None = None) -> str:
        """Navigate to a URL with realistic headers.
        
        Args:
            url: URL to navigate to
            extra_headers: Additional headers to merge with generated headers
        """
        if not url.startswith(("http://", "https://")):
            url = f"https://{url}"
        
        # Get realistic headers from browserforge
        all_headers = self.config.get_headers()
        
        # Merge any extra headers
        if extra_headers:
            all_headers = {**all_headers, **extra_headers}
        
        # Build the open command with headers
        args = ["open", url, "--headers", json.dumps(all_headers)]
        
        # Add user-agent
        user_agent = self.config.get_user_agent()
        if user_agent:
            args.extend(["--user-agent", user_agent])
        
        # Add headed mode
        if self.config.headed:
            args.append("--headed")
        
        # Add browser args
        if self.config.browser_args:
            args.extend(["--args", ",".join(self.config.browser_args)])
        
        result = self._run_command(*args, timeout=60.0)
        self._is_open = True
        self._current_url = url
        logger.info(f"Opened: {url}")
        return result
    
    def inject_fingerprint_spoof(self) -> str:
        """Inject JavaScript to spoof browser fingerprint."""
        return self.eval_js(FINGERPRINT_SPOOF_JS)
    
    def snapshot(self, interactive: bool = False) -> dict[str, Any]:
        """Get the accessibility tree snapshot for AI agents."""
        args = ["snapshot"]
        if interactive:
            args.append("-i")
        result = self._run_command(*args, json_output=True, timeout=30.0)
        return json.loads(result) if result else {}
    
    def click(self, selector: str) -> str:
        """Click an element by selector or @ref."""
        return self._run_command("click", selector)
    
    def fill(self, selector: str, text: str) -> str:
        """Clear and fill an input element."""
        return self._run_command("fill", selector, text)
    
    def type_text(self, selector: str, text: str) -> str:
        """Type into an element without clearing first."""
        return self._run_command("type", selector, text)
    
    def press(self, key: str) -> str:
        """Press a key (Enter, Tab, Escape, etc.)."""
        return self._run_command("press", key)
    
    def hover(self, selector: str) -> str:
        """Hover over an element."""
        return self._run_command("hover", selector)
    
    def scroll(self, direction: str, pixels: int = 500) -> str:
        """Scroll the page (up/down/left/right)."""
        return self._run_command("scroll", direction, str(pixels))
    
    def screenshot(self, path: str, full_page: bool = False) -> str:
        """Take a screenshot."""
        args = ["screenshot", path]
        if full_page:
            args.append("--full")
        return self._run_command(*args, timeout=30.0)
    
    def get_text(self, selector: str | None = None) -> str:
        """Get text content from the page or a specific element."""
        if selector:
            return self._run_command("get", "text", selector)
        return self._run_command("get", "text")
    
    def get_html(self, selector: str | None = None) -> str:
        """Get HTML content from the page or a specific element."""
        if selector:
            return self._run_command("get", "html", selector)
        return self._run_command("get", "html")
    
    def get_url(self) -> str:
        """Get the current page URL."""
        return self._run_command("get", "url")
    
    def get_title(self) -> str:
        """Get the current page title."""
        return self._run_command("get", "title")
    
    def eval_js(self, script: str) -> str:
        """Execute JavaScript in the browser."""
        return self._run_command("eval", script)
    
    def wait(self, selector_or_ms: str | int) -> str:
        """Wait for an element or a specific time."""
        return self._run_command("wait", str(selector_or_ms))
    
    def back(self) -> str:
        """Go back in browser history."""
        return self._run_command("back")
    
    def forward(self) -> str:
        """Go forward in browser history."""
        return self._run_command("forward")
    
    def reload(self) -> str:
        """Reload the current page."""
        return self._run_command("reload")
    
    def new_tab(self, url: str | None = None) -> str:
        """Open a new tab, optionally with a URL."""
        args = ["tab", "new"]
        if url:
            args.append(url)
        return self._run_command(*args)
    
    def switch_tab(self, tab_number: int) -> str:
        """Switch to a specific tab by number."""
        return self._run_command("tab", str(tab_number))
    
    def close_tab(self, tab_number: int | None = None) -> str:
        """Close the current tab or a specific tab."""
        args = ["tab", "close"]
        if tab_number is not None:
            args.append(str(tab_number))
        return self._run_command(*args)
    
    def list_tabs(self) -> list[dict[str, Any]]:
        """List all open tabs."""
        result = self._run_command("tab", "list", json_output=True)
        return json.loads(result) if result else []
    
    def set_headers(self, headers: dict[str, str]) -> str:
        """Set global HTTP headers for all requests."""
        return self._run_command("set", "headers", json.dumps(headers))
    
    def get_cookies(self) -> list[dict[str, Any]]:
        """Get all cookies."""
        result = self._run_command("cookies", json_output=True)
        return json.loads(result) if result else []
    
    def set_cookie(self, name: str, value: str, **options: Any) -> str:
        """Set a cookie."""
        args = ["cookies", "set", name, value]
        for key, val in options.items():
            args.extend([f"--{key}", str(val)])
        return self._run_command(*args)
    
    def clear_cookies(self) -> str:
        """Clear all cookies."""
        return self._run_command("cookies", "clear")
    
    def close(self) -> str:
        """Close the browser."""
        try:
            result = self._run_command("close")
        except RuntimeError as e:
            logger.warning(f"Error closing browser: {e}")
            result = "closed"
        finally:
            self._is_open = False
            self._current_url = None
            # Clean up config file
            if self._config_file and self._config_file.exists():
                try:
                    self._config_file.unlink()
                except Exception:
                    pass
                self._config_file = None
        return result
    
    def __enter__(self) -> "AgentBrowser":
        """Context manager entry."""
        return self.start()
    
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None:
        """Context manager exit - ensure browser is closed."""
        self.close()


def create_stealth_config_for_site(site_url: str) -> StealthConfig:
    """Create a stealth configuration optimized for a specific site.
    
    This can be extended to provide site-specific configurations
    for better anti-detection.
    """
    config = StealthConfig()
    
    # Site-specific adjustments can be added here
    if "homegate.ch" in site_url:
        # homegate.ch uses DataDome - extra stealth needed
        config.headed = True  # Always use headed mode
        config.locale = ["de-CH", "de", "en-US", "en"]  # Swiss German preferred
    
    return config


# Convenience function for quick browser tasks
def quick_open(url: str, headed: bool = True) -> tuple[AgentBrowser, dict[str, Any]]:
    """Open a URL with stealth and return browser + snapshot.
    
    Caller is responsible for calling browser.close() when done.
    """
    config = StealthConfig(headed=headed)
    browser = AgentBrowser(config)
    browser.start()
    browser.open(url)
    time.sleep(2)  # Wait for page load
    
    # Inject fingerprint spoofing
    try:
        browser.inject_fingerprint_spoof()
    except Exception as e:
        logger.warning(f"Failed to inject fingerprint spoofing: {e}")
    
    snapshot = browser.snapshot(interactive=True)
    return browser, snapshot
